### ISSUE TITLE
policy-controller template is out-of-date

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-tigera-secure-ee#2]
The [policy-controller template](https://github.com/juju-solutions/layer-tigera-secure-ee/blob/gkk/tigera-ee/templates/policy-controller.yaml) hasn't been updated in a long long time. It's not even called that anymore. It's called kube-controllers.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1813340.
