### ISSUE TITLE
registry-credentials config handler obliterates existing docker config.json

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-tigera-secure-ee#3]
https://github.com/juju-solutions/layer-tigera-secure-ee/blob/e2b34359958e48cdf264fb67b7e6d74c97d7c96e/reactive/calico.py#L334-L338

The kubernetes-worker charm also writes to `/root/.docker/config.json`, and this conflicts with that.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1813341.
