### ISSUE TITLE
can't pull cnx-node image on master units when using docker-registry charm with TLS enabled

### ISSUE THREAD

**Issue by Cynerva** [juju-solutions/layer-tigera-secure-ee#6]
After following the guide here: https://www.ubuntu.com/kubernetes/docs/docker-registry

I configured tigera-secure-ee to use the registry:
```
juju config tigera-secure-ee registry=<REGISTRY_IP>
```

On kubernetes-master units, the calico-node service did not come up, as they were unable to pull the image. The kubernetes-worker units came up fine.

I believe the kubernetes-master units need to do what the worker is doing [here](https://github.com/juju-solutions/kubernetes/blob/5abbb2f59d8bca91942ac61348702112b13e8731/cluster/juju/layers/kubernetes-worker/reactive/kubernetes_worker.py#L1295-L1298): configure docker with a CA cert and client certs.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1813343.
